name: Actualizar RSS Crunchyroll

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Esto asegura que no te dé el error 403 de permisos

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias de Python
        run: pip install -r requirements.txt

      - name: Instalar navegador (Playwright)
        run: playwright install chromium --with-deps

      - name: Ejecutar el rastreador
        run: python scraper.py

      - name: Guardar cambios en el RSS
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add feed.xml
          git commit -m "Actualización del feed RSS" || exit 0
          git push
